package com.tetra.app;

import android.content.Context;
import android.graphics.Canvas;
import android.graphics.Color;
import android.graphics.Paint;
import android.graphics.pdf.PdfDocument;
import android.os.Environment;
import android.util.Log;

import java.io.File;
import java.io.FileOutputStream;
import java.io.IOException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.List;
import java.util.Locale;

public class PDFJournalService {

    private static final String TAG = "PDFJournalService";
    private static final int PAGE_WIDTH = 595;   // A4 width in points
    private static final int PAGE_HEIGHT = 842;  // A4 height in points
    private static final int MARGIN = 40;
    private static final int LINE_HEIGHT = 22;

    private final Context context;

    public PDFJournalService(Context context) {
        this.context = context;
    }

    public String exportToPDF(List<ChatMessage> messages) {
        PdfDocument document = new PdfDocument();

        // --- Paints ---
        Paint brandPaint = new Paint();
        brandPaint.setColor(Color.parseColor("#1A237E")); // Deep indigo
        brandPaint.setTextSize(22f);
        brandPaint.setFakeBoldText(true);

        Paint subPaint = new Paint();
        subPaint.setColor(Color.parseColor("#5C6BC0"));
        subPaint.setTextSize(12f);

        Paint datePaint = new Paint();
        datePaint.setColor(Color.DKGRAY);
        datePaint.setTextSize(11f);

        Paint userPaint = new Paint();
        userPaint.setColor(Color.parseColor("#1B5E20")); // Dark green
        userPaint.setTextSize(13f);
        userPaint.setFakeBoldText(true);

        Paint aiPaint = new Paint();
        aiPaint.setColor(Color.parseColor("#BF360C")); // Deep orange
        aiPaint.setTextSize(13f);
        aiPaint.setFakeBoldText(true);

        Paint bodyPaint = new Paint();
        bodyPaint.setColor(Color.BLACK);
        bodyPaint.setTextSize(13f);

        Paint dividerPaint = new Paint();
        dividerPaint.setColor(Color.LTGRAY);
        dividerPaint.setStrokeWidth(1f);

        // --- Page setup ---
        PdfDocument.PageInfo pageInfo = new PdfDocument.PageInfo.Builder(PAGE_WIDTH, PAGE_HEIGHT, 1).create();
        PdfDocument.Page page = document.startPage(pageInfo);
        Canvas canvas = page.getCanvas();
        int pageNum = 1;
        int y = MARGIN;

        // --- Header ---
        canvas.drawText("TETRA", MARGIN, y + 22, brandPaint);
        y += 28;
        canvas.drawText("Truthful Guidance Journal", MARGIN, y, subPaint);
        y += 18;

        String timestamp = new SimpleDateFormat("dd MMM yyyy, hh:mm a", Locale.getDefault())
                .format(new Date());
        canvas.drawText("Session: " + timestamp, MARGIN, y, datePaint);
        y += 8;
        canvas.drawLine(MARGIN, y, PAGE_WIDTH - MARGIN, y, dividerPaint);
        y += 20;

        // --- Messages ---
        for (ChatMessage msg : messages) {
            // Check if we need a new page
            if (y > PAGE_HEIGHT - 80) {
                document.finishPage(page);
                pageNum++;
                PdfDocument.PageInfo newPageInfo = new PdfDocument.PageInfo.Builder(PAGE_WIDTH, PAGE_HEIGHT, pageNum).create();
                page = document.startPage(newPageInfo);
                canvas = page.getCanvas();
                y = MARGIN;
            }

            boolean isUser = msg.getRole() == ChatMessage.Role.USER;
            String label = isUser ? "You:" : "TETRA:";
            Paint labelPaint = isUser ? userPaint : aiPaint;

            canvas.drawText(label, MARGIN, y, labelPaint);
            y += LINE_HEIGHT;

            // Word wrap the message text
            String text = msg.getText();
            List<String> lines = wrapText(text, bodyPaint, PAGE_WIDTH - (MARGIN * 2));
            for (String line : lines) {
                if (y > PAGE_HEIGHT - 60) {
                    document.finishPage(page);
                    pageNum++;
                    PdfDocument.PageInfo newPageInfo = new PdfDocument.PageInfo.Builder(PAGE_WIDTH, PAGE_HEIGHT, pageNum).create();
                    page = document.startPage(newPageInfo);
                    canvas = page.getCanvas();
                    y = MARGIN;
                }
                canvas.drawText(line, MARGIN + 10, y, bodyPaint);
                y += LINE_HEIGHT;
            }

            // Divider between messages
            canvas.drawLine(MARGIN, y, PAGE_WIDTH - MARGIN, y, dividerPaint);
            y += 14;
        }

        // --- Footer ---
        Paint footerPaint = new Paint();
        footerPaint.setColor(Color.GRAY);
        footerPaint.setTextSize(10f);
        canvas.drawText("Generated by TETRA - Your Offline Truthful Mentor", MARGIN, PAGE_HEIGHT - 20, footerPaint);

        document.finishPage(page);

        // --- Save file ---
        String fileName = "TETRA_Journal_" +
                new SimpleDateFormat("yyyyMMdd_HHmmss", Locale.getDefault()).format(new Date()) + ".pdf";

        File docsDir = Environment.getExternalStoragePublicDirectory(Environment.DIRECTORY_DOCUMENTS);
        if (!docsDir.exists()) docsDir.mkdirs();

        File pdfFile = new File(docsDir, fileName);

        try (FileOutputStream fos = new FileOutputStream(pdfFile)) {
            document.writeTo(fos);
            Log.d(TAG, "PDF saved: " + pdfFile.getAbsolutePath());
            return pdfFile.getAbsolutePath();
        } catch (IOException e) {
            Log.e(TAG, "Failed to save PDF", e);
            return null;
        } finally {
            document.close();
        }
    }

    // Word wrap helper
    private List<String> wrapText(String text, Paint paint, int maxWidth) {
        List<String> lines = new java.util.ArrayList<>();
        String[] words = text.split(" ");
        StringBuilder currentLine = new StringBuilder();

        for (String word : words) {
            String testLine = currentLine.length() == 0 ? word : currentLine + " " + word;
            if (paint.measureText(testLine) <= maxWidth) {
                currentLine = new StringBuilder(testLine);
            } else {
                if (currentLine.length() > 0) lines.add(currentLine.toString());
                currentLine = new StringBuilder(word);
            }
        }
        if (currentLine.length() > 0) lines.add(currentLine.toString());
        return lines;
    }
}
